# Generated by Django 5.1.6 on 2025-03-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loan_amount_paid_loan_created_at_loan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED')], default='ACTIVE', max_length=10),
        ),
    ]
