# Generated by Django 5.1.6 on 2025-03-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_loan_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
